// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPhM3plg_1abca8R474cFNZvIyskQYgyA',
    appId: '1:623235027274:web:59456cd11e75077c39b1b3',
    messagingSenderId: '623235027274',
    projectId: 'login-app-d0d85',
    authDomain: 'login-app-d0d85.firebaseapp.com',
    storageBucket: 'login-app-d0d85.firebasestorage.app',
    measurementId: 'G-6LSY2K608N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1G6ogGAgKR5s0smWq2suMIKxtKju_A_Y',
    appId: '1:623235027274:android:2c561c4cade511cd39b1b3',
    messagingSenderId: '623235027274',
    projectId: 'login-app-d0d85',
    storageBucket: 'login-app-d0d85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC_pr1zFj6lgIDNFnRcbJl_pszZ_mJKLI',
    appId: '1:623235027274:ios:761b52f43071a4df39b1b3',
    messagingSenderId: '623235027274',
    projectId: 'login-app-d0d85',
    storageBucket: 'login-app-d0d85.firebasestorage.app',
    iosBundleId: 'com.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC_pr1zFj6lgIDNFnRcbJl_pszZ_mJKLI',
    appId: '1:623235027274:ios:761b52f43071a4df39b1b3',
    messagingSenderId: '623235027274',
    projectId: 'login-app-d0d85',
    storageBucket: 'login-app-d0d85.firebasestorage.app',
    iosBundleId: 'com.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPhM3plg_1abca8R474cFNZvIyskQYgyA',
    appId: '1:623235027274:web:79aa0ece106cc09939b1b3',
    messagingSenderId: '623235027274',
    projectId: 'login-app-d0d85',
    authDomain: 'login-app-d0d85.firebaseapp.com',
    storageBucket: 'login-app-d0d85.firebasestorage.app',
    measurementId: 'G-LJTMQDYHGW',
  );
}
